config/routes.rb
Server::Application.routes.draw do
  devise_for :employees
  devise_for :devices, :only => nil #only auth token

  constraints :host => /^(?!api\.)/ do
    namespace :frontoffice, :path => '' do
      root :to => 'restaurants#index'

      resources :restaurants do
        resources :zones
        resources :tables
        resources :waiters
      end

      resources :menus
      resources :product_types
      resources :products

      resources :employees

      match 'monitoring' => 'monitoring#index'
    end
  end

  constraints :host => /^api\./ do
    namespace :api, :path => '' do
      match 'restaurant' => 'restaurant#show', :via => :get

      resources :orders, :only => [:index, :create, :update]

      match 'register' => 'device#register', :via => :post
    end
  end
end

app/models/restaurant.rb
class Restaurant
  include Mongoid::Document
  include Mongoid::Slug

  field :name
  field :address
  field :menu_begin_date, type: Date
  field :menu_end_date, type: Date

  has_many :zones, :dependent => :delete
  has_many :tables, :dependent => :delete
  has_many :waiters, :dependent => :delete
  belongs_to :menu

  slug :name
  validates :name, presence: true, uniqueness: true
  validate :begin_date_before_end_date

  acts_as_api
  api_accessible :public do |t|
    t.add :menu_begin_date
    t.add :menu_end_date
    t.add :menu
  end

  protected
  def begin_date_before_end_date
    if menu_begin_date > menu_end_date
      errors.add(:menu_end_date, "can't be before menu begin date")
    end
  end
end

app/controllers/api/restaurant_controller.rb
class Api::RestaurantController < Api::ApiController
  def show
    @restaurant = current_device.owner.restaurant

    respond_with :api, @restaurant, :api_template => :public
  end
end

app/controllers/frontoffice/employees_controller.rb
class Frontoffice::EmployeesController < Frontoffice::FrontofficeController
  def index
    @employees = Employee.all

    respond_with :frontoffice, @employees
  end

  def show
    @employee = Employee.find_by_slug(params[:id])

    respond_with :frontoffice, @employee
  end

  def new
    @employee = Employee.new

    respond_with :frontoffice, @employee
  end

  def edit
    @employee = Employee.find_by_slug(params[:id])

    respond_with :frontoffice, @employee
  end

  def create
    @employee = Employee.new(params[:employee])

    if @employee.save  
      flash[:notice] = "Successfully created employee."  
    end 

    respond_with :frontoffice, @employee
  end

  def update
    @employee = Employee.find_by_slug(params[:id])

    if @employee.update_attributes(params[:employee])
      flash[:notice] = "Successfully updated employee."  
    end

    respond_with :frontoffice, @employee
  end

  def destroy
    @employee = Employee.find_by_slug(params[:id])

    if @employee.is_admin
      flash[:error] = "Cannot destroy admin employee."

      respond_with :frontoffice, @employee, :location => frontoffice_employees_url
    else
      @employee.destroy

      flash[:notice] = "Successfully destroyed employee."

      respond_with :frontoffice, @employee
    end
  end
end

app/controllers/frontoffice/frontoffice_controller.rb
class Frontoffice::FrontofficeController < ApplicationController
  respond_to :html

  protect_from_forgery

  before_filter :authenticate_employee!
end

app/controllers/frontoffice/menus_controller.rb
class Frontoffice::MenusController < Frontoffice::FrontofficeController
  def index
    @menus = Menu.all

    respond_with :frontoffice, @menus
  end

  def show
    @menu = Menu.find_by_slug(params[:id])

    respond_with :frontoffice, @menu
  end

  def new
    @menu = Menu.new

    respond_with :frontoffice, @menu
  end

  def edit
    @menu = Menu.find_by_slug(params[:id])

    respond_with :frontoffice, @menu
  end

  def create
    @menu = Menu.new(params[:menu])

    if @menu.save  
      flash[:notice] = "Successfully created menu."  
    end 

    respond_with :frontoffice, @menu
  end

  def update
    @menu = Menu.find_by_slug(params[:id])

    if @menu.update_attributes(params[:menu])
      flash[:notice] = "Successfully updated menu."  
    end

    respond_with :frontoffice, @menu
  end

  def destroy
    @menu = Menu.find_by_slug(params[:id])
    @menu.destroy

    flash[:notice] = "Successfully destroyed menu."

    respond_with :frontoffice, @menu
  end
end

app/controllers/frontoffice/monitoring_controller.rb
class Frontoffice::MonitoringController < Frontoffice::FrontofficeController
  def index
    @orders = Order.all

    @orders = @orders.where

    unless (params[:restaurant].blank?)
      restaurant = Restaurant.find_by_slug(params[:restaurant])
      tables = Table.where(:zone_id.in => restaurant.zones.map(&:_id)) 
      @orders = @orders.where(:table_id.in => tables.map(&:_id))
    end

    unless (params[:product_type].blank?)
      product_type = ProductType.find_by_slug(params[:product_type])
      @orders = @orders.where(
                  "order_items" => {
                    "$elemMatch" => {
                      "product_id" => {
                        "$in" => product_type.products.map(&:_id)
                      }}})
    end
  end
end

app/controllers/frontoffice/product_types_controller.rb
class Frontoffice::ProductTypesController < Frontoffice::FrontofficeController
  def index
    @product_types = ProductType.all

    respond_with :frontoffice, @product_types
  end

  def show
    @product_type = ProductType.find_by_slug(params[:id])

    respond_with :frontoffice, @product_type
  end

  def new
    @product_type = ProductType.new

    respond_with :frontoffice, @product_type
  end

  def edit
    @product_type = ProductType.find_by_slug(params[:id])

    respond_with :frontoffice, @product_type
  end

  def create
    @product_type = ProductType.new(params[:product_type])

    if @product_type.save  
      flash[:notice] = "Successfully created product type."  
    end 

    respond_with :frontoffice, @product_type
  end

  def update
    @product_type = ProductType.find_by_slug(params[:id])

    if @product_type.update_attributes(params[:product_type])
      flash[:notice] = "Successfully updated product type."  
    end

    respond_with :frontoffice, @product_type
  end

  def destroy
    @product_type = ProductType.find_by_slug(params[:id])
    @product_type.destroy

    flash[:notice] = "Successfully destroyed product type."

    respond_with :frontoffice, @product_type
  end
end

app/controllers/frontoffice/products_controller.rb
class Frontoffice::ProductsController < Frontoffice::FrontofficeController
  def index
    @products = Product.all

    respond_with :frontoffice, @products
  end

  def show
    @product = Product.find_by_slug(params[:id])

    respond_with :frontoffice, @product
  end

  def new
    @product = Product.new

    respond_with :frontoffice, @product
  end

  def edit
    @product = Product.find_by_slug(params[:id])

    respond_with :frontoffice, @product
  end

  def create
    @product = Product.new(params[:product])

    if @product.save  
      flash[:notice] = "Successfully created product type."  
    end 

    respond_with :frontoffice, @product
  end

  def update
    @product = Product.find_by_slug(params[:id])

    if @product.update_attributes(params[:product])
      flash[:notice] = "Successfully updated product type."  
    end

    respond_with :frontoffice, @product
  end

  def destroy
    @product = Product.find_by_slug(params[:id])
    @product.destroy

    flash[:notice] = "Successfully destroyed product type."

    respond_with :frontoffice, @product
  end
end

app/controllers/frontoffice/restaurants_controller.rb
class Frontoffice::RestaurantsController < Frontoffice::FrontofficeController
  def index
    @restaurants = Restaurant.all

    respond_with :frontoffice, @restaurants
  end

  def show
    @restaurant = Restaurant.find_by_slug(params[:id])

    respond_with :frontoffice, @restaurant
  end

  def new
    @restaurant = Restaurant.new

    respond_with :frontoffice, @restaurant
  end

  def edit
    @restaurant = Restaurant.find_by_slug(params[:id])

    respond_with :frontoffice, @restaurant
  end

  def create
    @restaurant = Restaurant.new(params[:restaurant])

    if @restaurant.save  
      flash[:notice] = "Successfully created restaurant."  
    end 

    respond_with :frontoffice, @restaurant
  end

  def update
    @restaurant = Restaurant.find_by_slug(params[:id])

    if @restaurant.update_attributes(params[:restaurant])
      flash[:notice] = "Successfully updated restaurant."  
    end

    respond_with :frontoffice, @restaurant
  end

  def destroy
    @restaurant = Restaurant.find_by_slug(params[:id])
    @restaurant.destroy

    flash[:notice] = "Successfully destroyed restaurant."

    respond_with :frontoffice, @restaurant
  end
end

app/controllers/frontoffice/tables_controller.rb
class Frontoffice::TablesController < Frontoffice::FrontofficeController
  def index
    @restaurant = Restaurant.find_by_slug(params[:restaurant_id])
    @tables = @restaurant.tables

    respond_with :frontoffice, @restaurant, @tables
  end

  def show
    @table = Restaurant.find_by_slug(params[:restaurant_id]).tables.find_by_slug(params[:id])

    respond_with :frontoffice, @table.restaurant, @table
  end

  def new
    @table = Restaurant.find_by_slug(params[:restaurant_id]).tables.new

    respond_with :frontoffice, @table.restaurant, @table
  end

  def edit
    @table = Restaurant.find_by_slug(params[:restaurant_id]).tables.find_by_slug(params[:id])

    respond_with :frontoffice, @table.restaurant, @table
  end

  def create
    @table = Restaurant.find_by_slug(params[:restaurant_id]).tables.new(params[:table])
    @table.create_device

    if @table.save  
      flash[:notice] = "Successfully created table."  
    end 

    respond_with :frontoffice, @table.restaurant, @table
  end

  def update
    @table = Restaurant.find_by_slug(params[:restaurant_id]).tables.find_by_slug(params[:id])

    if @table.update_attributes(params[:table])
      flash[:notice] = "Successfully updated table."  
    end

    respond_with :frontoffice, @table.restaurant, @table
  end

  def destroy
    @table = Restaurant.find_by_slug(params[:restaurant_id]).tables.find_by_slug(params[:id])
    @table.destroy

    flash[:notice] = "Successfully destroyed table."

    respond_with :frontoffice, @table.restaurant, @table
  end
end

app/controllers/frontoffice/waiters_controller.rb
class Frontoffice::WaitersController < Frontoffice::FrontofficeController
  def index
    @restaurant = Restaurant.find_by_slug(params[:restaurant_id])
    @waiters = @restaurant.waiters

    respond_with :frontoffice, @restaurant, @waiters
  end

  def show
    @waiter = Restaurant.find_by_slug(params[:restaurant_id]).waiters.find_by_slug(params[:id])

    respond_with :frontoffice, @waiter.restaurant, @waiter
  end

  def new
    @waiter = Restaurant.find_by_slug(params[:restaurant_id]).waiters.new

    respond_with :frontoffice, @waiter.restaurant, @waiter
  end

  def edit
    @waiter = Restaurant.find_by_slug(params[:restaurant_id]).waiters.find_by_slug(params[:id])

    respond_with :frontoffice, @waiter.restaurant, @waiter
  end

  def create
    @waiter = Restaurant.find_by_slug(params[:restaurant_id]).waiters.new(params[:waiter])
    @waiter.create_device

    if params[:waiter][:zone]
      Zone.find(params[:waiter][:zone]).update_attributes(waiter: @waiter)
    end
    if @waiter.save
      flash[:notice] = "Successfully created waiter."  
    end 

    respond_with :frontoffice, @waiter.restaurant, @waiter
  end

  def update
    @waiter = Restaurant.find_by_slug(params[:restaurant_id]).waiters.find_by_slug(params[:id])

    if params[:waiter][:zone]
      Zone.find(params[:waiter][:zone]).update_attributes(waiter: @waiter)
      params[:waiter].delete(:zone)
    end
    if @waiter.update_attributes(params[:waiter])
      flash[:notice] = "Successfully updated waiter."  
    end

    respond_with :frontoffice, @waiter.restaurant, @waiter
  end

  def destroy
    @waiter = Restaurant.find_by_slug(params[:restaurant_id]).waiters.find_by_slug(params[:id])
    @waiter.destroy

    flash[:notice] = "Successfully destroyed waiter."

    respond_with :frontoffice, @waiter.restaurant, @waiter
  end
end

app/controllers/frontoffice/zones_controller.rb
class Frontoffice::ZonesController < Frontoffice::FrontofficeController
  def index
    @restaurant = Restaurant.find_by_slug(params[:restaurant_id])
    @zones = @restaurant.zones

    respond_with :frontoffice, @restaurant, @zones
  end

  def show
    @zone = Restaurant.find_by_slug(params[:restaurant_id]).zones.find_by_slug(params[:id])

    respond_with :frontoffice, @zone.restaurant, @zone
  end

  def new
    @zone = Restaurant.find_by_slug(params[:restaurant_id]).zones.new

    respond_with :frontoffice, @zone.restaurant, @zone
  end

  def edit
    @zone = Restaurant.find_by_slug(params[:restaurant_id]).zones.find_by_slug(params[:id])

    respond_with :frontoffice, @zone.restaurant, @zone
  end

  def create
    @zone = Restaurant.find_by_slug(params[:restaurant_id]).zones.new(params[:zone])

    if params[:zone][:waiter]
      Waiter.find(params[:zone][:waiter]).update_attributes(zone: @zone)
    end
    if @zone.save
      flash[:notice] = "Successfully created zone."  
    end 

    respond_with :frontoffice, @zone.restaurant, @zone
  end

  def update
    @zone = Restaurant.find_by_slug(params[:restaurant_id]).zones.find_by_slug(params[:id])

    if params[:zone][:waiter]
      Waiter.find(params[:zone][:waiter]).update_attributes(zone: @zone)
      params[:zone].delete(:waiter)
    end
    if @zone.update_attributes(params[:zone])
      flash[:notice] = "Successfully updated zone."  
    end

    respond_with :frontoffice, @zone.restaurant, @zone
  end

  def destroy
    @zone = Restaurant.find_by_slug(params[:restaurant_id]).zones.find_by_slug(params[:id])
    @zone.destroy

    flash[:notice] = "Successfully destroyed zone."

    respond_with :frontoffice, @zone.restaurant, @zone
  end
end

app/views/frontoffice/restaurants/_form.html.haml
= simple_form_for [:frontoffice, @restaurant], :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :address
  = f.input :menu, :collection => Menu.all, :selected => (@restaurant.menu.id if @restaurant.menu) unless Menu.empty?
  = f.input :menu_begin_date, :input_html => { :class => 'date_picker' }
  = f.input :menu_end_date, :input_html => { :class => 'date_picker' }
  = f.button :wrapped, :cancel => frontoffice_restaurants_path

app/views/frontoffice/restaurants/edit.html.haml
- model_class = @restaurant.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/frontoffice/restaurants/index.html.haml
- model_class = Restaurant
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:address)
      %th= model_class.human_attribute_name(:zones)
      %th= model_class.human_attribute_name(:tables)
      %th= model_class.human_attribute_name(:waiters)
      %th= model_class.human_attribute_name(:menu)
      %th= model_class.human_attribute_name(:menu_begin_date)
      %th= model_class.human_attribute_name(:menu_end_date)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @restaurants.each do |restaurant|
      %tr
        %td= link_to restaurant.name, frontoffice_restaurant_path(restaurant)
        %td= restaurant.address
        %td= link_to 'Zones', frontoffice_restaurant_zones_path(restaurant)
        %td= link_to 'Tables', frontoffice_restaurant_tables_path(restaurant)
        %td= link_to 'Waiters', frontoffice_restaurant_waiters_path(restaurant)
        %td= link_to restaurant.menu.name, frontoffice_menu_path(restaurant.menu) if restaurant.menu
        %td= restaurant.menu_begin_date
        %td= restaurant.menu_end_date
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_frontoffice_restaurant_path(restaurant), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), frontoffice_restaurant_path(restaurant), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_frontoffice_restaurant_path, :class => 'btn btn-primary'

app/views/frontoffice/restaurants/new.html.haml
- model_class = @restaurant.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/frontoffice/restaurants/show.html.haml
- model_class = @restaurant.class
%h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @restaurant.name

%p
  %strong= model_class.human_attribute_name(:address) + ':'
  %br
  = @restaurant.address

- if @restaurant.menu
  %p
    %strong= model_class.human_attribute_name(:menu) + ':'
    %br
    = link_to @restaurant.menu.name, frontoffice_menu_path(@restaurant.menu)
  %p
    %strong= model_class.human_attribute_name(:menu_begin_date) + ':'
    %br
    = @restaurant.menu_begin_date
  %p
    %strong= model_class.human_attribute_name(:menu_end_date) + ':'
    %br
    = @restaurant.menu_end_date

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), frontoffice_restaurants_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_frontoffice_restaurant_path(@restaurant), :class => 'btn'
  = link_to t('.edit_zones', :default => t("helpers.links.edit_zones")), frontoffice_restaurant_zones_path(@restaurant), :class => 'btn'
  = link_to t('.edit_tables', :default => t("helpers.links.edit_tables")), frontoffice_restaurant_tables_path(@restaurant), :class => 'btn'
  = link_to t('.edit_waiters', :default => t("helpers.links.edit_waiters")), frontoffice_restaurant_waiters_path(@restaurant), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), frontoffice_restaurant_path(@restaurant), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'