config/routes.rb
Server::Application.routes.draw do
  devise_for :employees
  devise_for :devices, :only => nil #only auth token

  constraints :host => /^(?!api\.)/ do
    namespace :frontoffice, :path => '' do
      root :to => 'restaurants#index'

      resources :restaurants do
        resources :zones
        resources :tables
        resources :waiters
      end

      resources :menus
      resources :product_types
      resources :products

      resources :employees

      match 'monitoring' => 'monitoring#index'
    end
  end

  constraints :host => /^api\./ do
    namespace :api, :path => '' do
      match 'restaurant' => 'restaurant#show', :via => :get

      resources :orders, :only => [:index, :create, :update]

      match 'register' => 'device#register', :via => :post
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YouFood</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">  
  <div class="navbar-inner">  
    <div class="container">  
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".collapse">  
        <span class="icon-bar"></span>  
        <span class="icon-bar"></span>  
        <span class="icon-bar"></span>  
      </a>  
      <%= link_to "YouFood", frontoffice_root_path, :class => 'brand' %>  
      <div class="nav-collapse">  
        <ul class="nav">  
          <li><%= link_to "Restaurants", frontoffice_restaurants_path %></li>
          <li><%= link_to "Menus", frontoffice_menus_path %></li>
          <li><%= link_to "Product Types", frontoffice_product_types_path %></li>
          <li><%= link_to "Products", frontoffice_products_path %></li>
          <li><%= link_to "Employees", frontoffice_employees_path %></li>
          <li><%= link_to "Monitoring", frontoffice_monitoring_path %></li>
        </ul>
        <ul class="nav pull-right">
          <% if employee_signed_in? %>
            <li>
            <%= link_to('Logout', destroy_employee_session_path, :method => :delete) %>   
            </li>
          <% else %>
            <li>
            <%= link_to('Login', new_employee_session_path)  %>  
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-info">
    <%= flash[:notice] %>
    </div>
  <% end %>
  <% if flash[:error] %>
    <div class="alert alert-error">
    <%= flash[:error] %>
    </div>
  <% end %>
  <%= yield %>
</div>

<%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/frontoffice.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YouFood</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">  
  <div class="navbar-inner">  
    <div class="container">  
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".collapse">  
        <span class="icon-bar"></span>  
        <span class="icon-bar"></span>  
        <span class="icon-bar"></span>  
      </a>  
      <%= link_to "YouFood", frontoffice_root_path, :class => 'brand' %>  
      <div class="nav-collapse">  
        <ul class="nav">  
          <li><%= link_to "Restaurants", frontoffice_restaurants_path %></li>
          <li><%= link_to "Menus", frontoffice_menus_path %></li>
          <li><%= link_to "Product Types", frontoffice_product_types_path %></li>
          <li><%= link_to "Products", frontoffice_products_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>

<%= javascript_include_tag "application" %>
</body>
</html>